### ISSUE TITLE
Дюп падающих блоков через стражей

### ISSUE THREAD

**Issue by Cactus998** [F3F5/FallingBlockFix#2]
Если настакать в 1 блоке 3 и более стражей, то скинув на них песок, гравий, наковальню, блок дюпнется. то есть выпадет как айтем, но при этом ещё и останется как блок.

**Comment by F3F5** [comment]
> Если настакать в 1 блоке 3 и более стражей, то скинув на них песок, гравий, наковальню, блок дюпнется. то есть выпадет как айтем, но при этом ещё и останется как блок.

а можно видео?

**Comment by Cactus998** [comment]
ок завтра запишу

**Comment by F3F5** [comment]
**плагин возможно переделается в будущем, он не оптимизирован, так же код грязный изза того что я свой же плагин декомплировал**

**Comment by F3F5** [comment]
закрыт за неактив.
